### ISSUE TITLE
Can not create connection to MongoDB version 3.4.0

### ISSUE THREAD

**Issue by CarlosCamposGalo** [scttnlsn/mubsub#54] opened 2016-12-16 00:38 UTC
Was not able to create connection

> client = mubsub("#{env.mongodb_url}/mubsub")
> channel = client.channel('alerts', {size: 10000, max: 100})

Was able to connect after **retryInterval** and **recreate** options were remove in lib/channel.js

**Comment by hacksut3l** [comment] 2016-12-17 05:53
+1

**Comment by adrianbon** [comment] 2016-12-28 20:51
+1

**Comment by scttnlsn** [comment] 2017-01-12 15:23
Duplicate of https://github.com/scttnlsn/mubsub/pull/55 (merged)

**Closed by scttnlsn** 2017-01-12 15:23 UTC
